language: python
python:
  - "3.6"

install: 
  - pip install -r requirements.txt

script:
  - cd src && python3 -m unittest discover ../test/ && cd ..
  - black --check --verbose src/.

branches:
  only:
  - master