language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "3.1"
  - "3.0"

install: 
  - pip install -r requirements.txt

script:
  - cd src && python3 -m unittest discover ../test/

branches:
  only:
  - master